package org.apache.cxf.systest.https.hostname;

import org.apache.cxf.systest.https.hostname.types.FaultDetail;

import javax.annotation.Generated;
import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.0-SNAPSHOT-da5b01b32a59867b48e2b35a9281b3625f58d514
 * 2018-07-05T11:48:08.409-03:00
 * Generated source version: 3.3.0-SNAPSHOT
 */

@WebFault(name = "faultDetail", targetNamespace = "http://apache.org/hello_world/types")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-07-05T11:48:08.409-03:00", comments = "Apache CXF 3.3.0-SNAPSHOT-da5b01b32a59867b48e2b35a9281b3625f58d514")
public class PingMeFault extends Exception {
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-07-05T11:48:08.409-03:00")
    public static final long serialVersionUID = 1L;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-07-05T11:48:08.409-03:00")
    private FaultDetail faultDetail;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-07-05T11:48:08.409-03:00")
    public PingMeFault() {
        super();
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-07-05T11:48:08.409-03:00")
    public PingMeFault(String message) {
        super(message);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-07-05T11:48:08.409-03:00")
    public PingMeFault(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-07-05T11:48:08.409-03:00")
    public PingMeFault(String message, FaultDetail faultDetail) {
        super(message);
        this.faultDetail = faultDetail;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-07-05T11:48:08.409-03:00")
    public PingMeFault(String message, FaultDetail faultDetail, java.lang.Throwable cause) {
        super(message, cause);
        this.faultDetail = faultDetail;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-07-05T11:48:08.409-03:00")
    public FaultDetail getFaultInfo() {
        return this.faultDetail;
    }
}