package org.apache.cxf.systest.https.hostname;


import java.net.MalformedURLException;
import java.net.URL;
import javax.annotation.Generated;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0-SNAPSHOT-da5b01b32a59867b48e2b35a9281b3625f58d514
 * 2018-07-05T11:48:08.412-03:00
 * Generated source version: 3.3.0-SNAPSHOT
 *
 */
@WebServiceClient(name = "SOAPService",
        wsdlLocation = "file:/home/otaviojava/Environment/code/workspace-tomitribe-support/apache/cxf/testutils/src/main/resources/wsdl/hello_world_services.wsdl",
        targetNamespace = "http://apache.org/hello_world/services")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-07-05T11:48:08.412-03:00", comments = "Apache CXF 3.3.0-SNAPSHOT-da5b01b32a59867b48e2b35a9281b3625f58d514")
public class SOAPService extends Service {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-07-05T11:48:08.412-03:00")
    public final static URL WSDL_LOCATION;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-07-05T11:48:08.412-03:00")
    public final static QName SERVICE = new QName("http://apache.org/hello_world/services", "SOAPService");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-07-05T11:48:08.412-03:00")
    public final static QName SoapPort = new QName("http://apache.org/hello_world/services", "SoapPort");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-07-05T11:48:08.412-03:00")
    public final static QName HttpsPort = new QName("http://apache.org/hello_world/services", "HttpsPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/otaviojava/Environment/code/workspace-tomitribe-support/apache/cxf/testutils/src/main/resources/wsdl/hello_world_services.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SOAPService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "file:/home/otaviojava/Environment/code/workspace-tomitribe-support/apache/cxf/testutils/src/main/resources/wsdl/hello_world_services.wsdl");
        }
        WSDL_LOCATION = url;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-07-05T11:48:08.412-03:00")
    public SOAPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-07-05T11:48:08.412-03:00")
    public SOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-07-05T11:48:08.412-03:00")
    public SOAPService() {
        super(WSDL_LOCATION, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-07-05T11:48:08.412-03:00")
    public SOAPService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-07-05T11:48:08.412-03:00")
    public SOAPService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-07-05T11:48:08.412-03:00")
    public SOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Greeter
     */
    @WebEndpoint(name = "SoapPort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-07-05T11:48:08.412-03:00")
    public Greeter getSoapPort() {
        return super.getPort(SoapPort, Greeter.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Greeter
     */
    @WebEndpoint(name = "SoapPort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-07-05T11:48:08.412-03:00")
    public Greeter getSoapPort(WebServiceFeature... features) {
        return super.getPort(SoapPort, Greeter.class, features);
    }


    /**
     *
     * @return
     *     returns Greeter
     */
    @WebEndpoint(name = "HttpsPort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-07-05T11:48:08.412-03:00")
    public Greeter getHttpsPort() {
        return super.getPort(HttpsPort, Greeter.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Greeter
     */
    @WebEndpoint(name = "HttpsPort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-07-05T11:48:08.412-03:00")
    public Greeter getHttpsPort(WebServiceFeature... features) {
        return super.getPort(HttpsPort, Greeter.class, features);
    }

}